### PR TITLE
Default vd2 admin user fix

### PR DESCRIPTION
**Pull request by jnduwamu**
Added new variable in defaults -> main.yaml : 
`admin_users: "admin"`

The variable can therefore be invoked in the config_vd2.sh with the default value of `admin`

### CODE REVIEW

**Review by NicoGGG — COMMENTED** [review]
Need to add a test that checks vd_config.sh has the correct admin user

**Comment by jnduwamu** [comment]
> Need to add a test that checks vd_config.sh has the correct admin user

I've added tests for `aws_ec2`, `local` and `default` scenarios.

I read the content of `config.sh` and check if it contains the line `VISUALDOOP_ADMIN=` which shows that `vd2` has an actual user defined. We can't really tell before hand the value of that user..

Adding `VISUALDOOP_ADMIN=admin `would mean that the test will fail whenever the user is different from `admin`.

**Review by NicoGGG — CHANGES_REQUESTED** [review]
Good but maybe test in one of the scenario that the variable admin_users works properly by checking the the value of VISUALDOOP_ADMIN.
Also test on the others that we have the correct default value.
You can change the admin_users value in the molecule.yaml file.

**Review by indexima-team — APPROVED** [review]

**Review by indexima-team — APPROVED** [review]

**Review by indexima-team — APPROVED** [review]

**Review by indexima-team — APPROVED** [review]
OK

**Review by NicoGGG — APPROVED** [review]

**Pull request merged**
